#!/bin/bash

###############################################################################
# VPC情報取得スクリプト
# Terraformデプロイに必要なVPC関連情報を自動取得
###############################################################################

set -e

REGION="${AWS_REGION:-ap-northeast-1}"

echo "=========================================="
echo "VPC情報を取得中..."
echo "Region: $REGION"
echo "=========================================="
echo ""

# VPC IDを取得
echo "📌 VPC一覧:"
aws ec2 describe-vpcs --region "$REGION" \
  --query 'Vpcs[].[VpcId,Tags[?Key==`Name`].Value|[0],CidrBlock]' \
  --output table

echo ""
read -p "使用するVPC IDを入力してください: " VPC_ID

# プライベートサブネットを取得
echo ""
echo "📌 プライベートサブネット一覧 (VPC: $VPC_ID):"
aws ec2 describe-subnets --region "$REGION" \
  --filters "Name=vpc-id,Values=$VPC_ID" \
  --query 'Subnets[?MapPublicIpOnLaunch==`false`].[SubnetId,AvailabilityZone,CidrBlock,Tags[?Key==`Name`].Value|[0]]' \
  --output table

echo ""
echo "最低2つのプライベートサブネットを選択してください（異なるAZ）"
read -p "1つ目のサブネットID: " SUBNET_1
read -p "2つ目のサブネットID: " SUBNET_2

# セキュリティグループを取得
echo ""
echo "📌 セキュリティグループ一覧 (VPC: $VPC_ID):"
aws ec2 describe-security-groups --region "$REGION" \
  --filters "Name=vpc-id,Values=$VPC_ID" \
  --query 'SecurityGroups[].[GroupId,GroupName,Description]' \
  --output table

echo ""
read -p "OpenSearchのセキュリティグループID: " OPENSEARCH_SG_ID

# Cognitoユーザープールを取得
echo ""
echo "📌 Cognito User Pool一覧:"
aws cognito-idp list-user-pools --region "$REGION" --max-results 20 \
  --query 'UserPools[].[Id,Name]' \
  --output table

echo ""
read -p "使用するUser Pool ID: " COGNITO_POOL_ID

# User Pool ARNを取得
COGNITO_ARN=$(aws cognito-idp describe-user-pool --region "$REGION" \
  --user-pool-id "$COGNITO_POOL_ID" \
  --query 'UserPool.Arn' \
  --output text)

# OpenSearchドメインエンドポイントを取得
echo ""
echo "📌 OpenSearchドメイン一覧:"
aws opensearch list-domain-names --region "$REGION" \
  --query 'DomainNames[].[DomainName]' \
  --output table

echo ""
read -p "使用するOpenSearchドメイン名: " OPENSEARCH_DOMAIN

OPENSEARCH_ENDPOINT=$(aws opensearch describe-domain --region "$REGION" \
  --domain-name "$OPENSEARCH_DOMAIN" \
  --query 'DomainStatus.Endpoint' \
  --output text)

# VPCエンドポイントの場合
if [[ $OPENSEARCH_ENDPOINT == "" ]]; then
  OPENSEARCH_ENDPOINT=$(aws opensearch describe-domain --region "$REGION" \
    --domain-name "$OPENSEARCH_DOMAIN" \
    --query 'DomainStatus.Endpoints.vpc' \
    --output text)
fi

# HTTPSプレフィックスを追加
OPENSEARCH_ENDPOINT="https://$OPENSEARCH_ENDPOINT"

# terraform.tfvarsファイルを生成
echo ""
echo "=========================================="
echo "terraform.tfvars を生成中..."
echo "=========================================="

cat > ../terraform/terraform.tfvars <<EOF
# Terraform Variables for Lambda Search API
# Auto-generated by get-vpc-info.sh

# AWS Configuration
aws_region  = "$REGION"
environment = "prod"

# OpenSearch Configuration
opensearch_domain_endpoint = "$OPENSEARCH_ENDPOINT"
opensearch_index_name      = "file-index"

# Cognito Configuration
cognito_user_pool_id  = "$COGNITO_POOL_ID"
cognito_user_pool_arn = "$COGNITO_ARN"

# VPC Configuration
vpc_id                       = "$VPC_ID"
private_subnet_ids           = ["$SUBNET_1", "$SUBNET_2"]
opensearch_security_group_id = "$OPENSEARCH_SG_ID"
EOF

echo ""
echo "✅ terraform.tfvars が生成されました"
echo ""
cat ../terraform/terraform.tfvars

echo ""
echo "=========================================="
echo "🎉 完了！"
echo "=========================================="
echo ""
echo "次のステップ:"
echo "1. cd ../terraform"
echo "2. terraform init"
echo "3. terraform plan"
echo "4. terraform apply"
echo ""
