AWSTemplateFormatVersion: '2010-09-09'
Description: 'EC2 Auto Scaling Group for File Processing Workers with Enhanced Resilience'

Parameters:
  Environment:
    Type: String
    Default: production
    AllowedValues:
      - development
      - staging
      - production
    Description: Environment name

  InstanceType:
    Type: String
    Default: t3.medium
    AllowedValues:
      - t3.small
      - t3.medium
      - t3.large
      - t3.xlarge
      - c5.large
      - c5.xlarge
    Description: EC2 instance type

  MinSize:
    Type: Number
    Default: 1
    MinValue: 0
    MaxValue: 10
    Description: Minimum number of instances

  MaxSize:
    Type: Number
    Default: 10
    MinValue: 1
    MaxValue: 100
    Description: Maximum number of instances

  DesiredCapacity:
    Type: Number
    Default: 2
    MinValue: 0
    MaxValue: 100
    Description: Desired number of instances

  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: EC2 Key Pair for SSH access

  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID

  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Subnet IDs for Auto Scaling Group

  QueueURL:
    Type: String
    Description: SQS Queue URL for file processing

  DLQueueURL:
    Type: String
    Description: Dead Letter Queue URL

  S3Bucket:
    Type: String
    Description: S3 bucket name for file storage

  OpenSearchEndpoint:
    Type: String
    Description: OpenSearch endpoint URL

Resources:
  # IAM Role for EC2 Instances
  EC2InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'FileProcessorEC2Role-${Environment}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
      Policies:
        - PolicyName: FileProcessingPermissions
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              # SQS Permissions
              - Effect: Allow
                Action:
                  - sqs:ReceiveMessage
                  - sqs:DeleteMessage
                  - sqs:GetQueueAttributes
                  - sqs:ChangeMessageVisibility
                Resource:
                  - !Ref QueueURL
                  - !Ref DLQueueURL
              - Effect: Allow
                Action:
                  - sqs:SendMessage
                Resource:
                  - !Ref DLQueueURL
              # S3 Permissions
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:ListBucket
                Resource:
                  - !Sub 'arn:aws:s3:::${S3Bucket}/*'
                  - !Sub 'arn:aws:s3:::${S3Bucket}'
              # OpenSearch Permissions
              - Effect: Allow
                Action:
                  - es:ESHttpPost
                  - es:ESHttpPut
                  - es:ESHttpGet
                Resource:
                  - !Sub 'arn:aws:es:${AWS::Region}:${AWS::AccountId}:domain/*'
              # CloudWatch Logs
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - logs:DescribeLogStreams
                Resource:
                  - !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/ec2/file-processor*'
              # CloudWatch Metrics
              - Effect: Allow
                Action:
                  - cloudwatch:PutMetricData
                Resource: '*'

  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref EC2InstanceRole

  # Security Group
  ProcessorSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub 'file-processor-sg-${Environment}'
      GroupDescription: Security group for file processor EC2 instances
      VpcId: !Ref VpcId
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub 'file-processor-sg-${Environment}'
        - Key: Environment
          Value: !Ref Environment

  # Launch Template
  LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: !Sub 'file-processor-lt-${Environment}'
      LaunchTemplateData:
        ImageId: !Sub '{{resolve:ssm:/aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64}}'
        InstanceType: !Ref InstanceType
        KeyName: !Ref KeyName
        IamInstanceProfile:
          Arn: !GetAtt EC2InstanceProfile.Arn
        SecurityGroupIds:
          - !Ref ProcessorSecurityGroup
        BlockDeviceMappings:
          - DeviceName: /dev/xvda
            Ebs:
              VolumeSize: 30
              VolumeType: gp3
              DeleteOnTermination: true
              Encrypted: true
        MetadataOptions:
          HttpTokens: required
          HttpPutResponseHopLimit: 1
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            set -e

            # Log output
            exec > >(tee /var/log/user-data.log)
            exec 2>&1

            echo "=== Starting File Processor Setup ==="

            # Update system
            dnf update -y

            # Install Python 3.11
            dnf install -y python3.11 python3.11-pip

            # Install system dependencies
            dnf install -y \
              poppler-utils \
              ImageMagick \
              ImageMagick-devel \
              file-devel \
              git \
              htop

            # Install Tesseract OCR
            dnf install -y tesseract tesseract-langpack-jpn tesseract-langpack-eng

            # Install CloudWatch agent
            wget https://s3.amazonaws.com/amazoncloudwatch-agent/amazon_linux/amd64/latest/amazon-cloudwatch-agent.rpm
            rpm -U ./amazon-cloudwatch-agent.rpm
            rm -f amazon-cloudwatch-agent.rpm

            # Create application directory
            mkdir -p /opt/file-processor
            cd /opt/file-processor

            # Download application code from S3
            # aws s3 cp s3://${S3Bucket}/python-worker.zip . --region ${AWS::Region}
            # unzip python-worker.zip

            # Install Python dependencies
            pip3.11 install -r requirements.txt

            # Create environment file
            cat > .env << EOF
            AWS_REGION=${AWS::Region}
            SQS_QUEUE_URL=${QueueURL}
            DLQ_QUEUE_URL=${DLQueueURL}
            S3_BUCKET=${S3Bucket}
            OPENSEARCH_ENDPOINT=${OpenSearchEndpoint}
            OPENSEARCH_INDEX=file-index
            LOG_LEVEL=INFO
            MAX_WORKERS=4
            MAX_RETRIES=3
            EOF

            # Create systemd service
            cat > /etc/systemd/system/file-processor.service << 'EOFS'
            [Unit]
            Description=File Processing Worker
            After=network.target

            [Service]
            Type=simple
            User=ec2-user
            WorkingDirectory=/opt/file-processor
            Environment="PATH=/usr/bin"
            EnvironmentFile=/opt/file-processor/.env
            ExecStart=/usr/bin/python3.11 /opt/file-processor/worker.py
            Restart=always
            RestartSec=10
            StandardOutput=journal
            StandardError=journal

            [Install]
            WantedBy=multi-user.target
            EOFS

            # Set permissions
            chown -R ec2-user:ec2-user /opt/file-processor

            # Enable and start service
            systemctl daemon-reload
            systemctl enable file-processor
            systemctl start file-processor

            echo "=== File Processor Setup Complete ==="

  # Auto Scaling Group
  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: !Sub 'file-processor-asg-${Environment}'
      LaunchTemplate:
        LaunchTemplateId: !Ref LaunchTemplate
        Version: !GetAtt LaunchTemplate.LatestVersionNumber
      MinSize: !Ref MinSize
      MaxSize: !Ref MaxSize
      DesiredCapacity: !Ref DesiredCapacity
      VPCZoneIdentifier: !Ref SubnetIds
      HealthCheckType: EC2
      HealthCheckGracePeriod: 300
      TerminationPolicies:
        - OldestInstance
      Tags:
        - Key: Name
          Value: !Sub 'file-processor-${Environment}'
          PropagateAtLaunch: true
        - Key: Environment
          Value: !Ref Environment
          PropagateAtLaunch: true
        - Key: Application
          Value: CISFileSearch
          PropagateAtLaunch: true

  # Scaling Policies
  ScaleUpPolicy:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AutoScalingGroupName: !Ref AutoScalingGroup
      PolicyType: TargetTrackingScaling
      TargetTrackingConfiguration:
        PredefinedMetricSpecification:
          PredefinedMetricType: ASGAverageCPUUtilization
        TargetValue: 70.0

  QueueDepthScalingPolicy:
    Type: AWS::AutoScaling::ScalingPolicy
    Properties:
      AutoScalingGroupName: !Ref AutoScalingGroup
      PolicyType: TargetTrackingScaling
      TargetTrackingConfiguration:
        CustomizedMetricSpecification:
          MetricName: ApproximateNumberOfMessagesVisible
          Namespace: AWS/SQS
          Statistic: Average
          Dimensions:
            - Name: QueueName
              Value: !GetAtt QueueURL.QueueName
        TargetValue: 100.0  # 1インスタンスあたり100メッセージを目標

  # CloudWatch Alarms
  HighCPUAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub 'file-processor-high-cpu-${Environment}'
      AlarmDescription: Alert when CPU usage is high
      MetricName: CPUUtilization
      Namespace: AWS/EC2
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 80
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: AutoScalingGroupName
          Value: !Ref AutoScalingGroup

  HighMemoryAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub 'file-processor-high-memory-${Environment}'
      AlarmDescription: Alert when memory usage is high
      MetricName: mem_used_percent
      Namespace: CWAgent
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: 80
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: AutoScalingGroupName
          Value: !Ref AutoScalingGroup

Outputs:
  AutoScalingGroupName:
    Description: Name of the Auto Scaling Group
    Value: !Ref AutoScalingGroup
    Export:
      Name: !Sub '${AWS::StackName}-ASGName'

  LaunchTemplateId:
    Description: ID of the Launch Template
    Value: !Ref LaunchTemplate
    Export:
      Name: !Sub '${AWS::StackName}-LaunchTemplateId'

  SecurityGroupId:
    Description: Security Group ID
    Value: !Ref ProcessorSecurityGroup
    Export:
      Name: !Sub '${AWS::StackName}-SecurityGroupId'

  InstanceRoleArn:
    Description: IAM Role ARN for EC2 instances
    Value: !GetAtt EC2InstanceRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-InstanceRoleArn'
