#!/bin/bash
# ASG User Data Script for Preview Worker
# This script runs on every instance launch in the Auto Scaling Group
#
# Prerequisites:
# - AMI must have Python, dependencies, and worker code pre-installed at /opt/cis-file-processor
# - IAM Instance Profile must have permissions for SQS, S3, OpenSearch
#
set -ex

# Log all output for debugging
exec > >(tee /var/log/user-data.log|logger -t user-data -s 2>/dev/console) 2>&1

echo "=========================================="
echo "CIS Preview Worker - ASG Instance Bootstrap"
echo "Started at: $(date)"
echo "Instance ID: $(curl -s http://169.254.169.254/latest/meta-data/instance-id)"
echo "=========================================="

# -----------------------------------------------------------------------------
# CONFIGURATION - Update these values for your environment
# -----------------------------------------------------------------------------
APP_DIR="/opt/cis-file-processor"
LOG_DIR="/var/log/cis-worker"
WORKER_USER="cis-worker"

# AWS Configuration (these can also be set via Parameter Store / Secrets Manager)
AWS_REGION="ap-northeast-1"
PREVIEW_QUEUE_URL="https://sqs.ap-northeast-1.amazonaws.com/770923989980/cis-filesearch-preview-queue"
OPENSEARCH_ENDPOINT="https://search-cis-opensearch-xxxxxxxxx.ap-northeast-1.es.amazonaws.com"
OPENSEARCH_INDEX_NAME="cis-files"
S3_LANDING_BUCKET="cis-landing-bucket"
S3_THUMBNAIL_BUCKET="cis-thumbnail-bucket"

# Worker Configuration
WORKER_THREADS=2
IDLE_TIMEOUT=300

# -----------------------------------------------------------------------------
# STEP 1: Ensure directories exist with correct permissions
# -----------------------------------------------------------------------------
echo "Step 1: Creating directories..."

mkdir -p ${LOG_DIR}
mkdir -p ${APP_DIR}/temp

# Ensure user exists
if ! id -u ${WORKER_USER} > /dev/null 2>&1; then
    useradd -r -s /bin/false ${WORKER_USER}
fi

chown -R ${WORKER_USER}:${WORKER_USER} ${LOG_DIR}
chown -R ${WORKER_USER}:${WORKER_USER} ${APP_DIR}/temp
chmod 755 ${LOG_DIR}

# -----------------------------------------------------------------------------
# STEP 2: Create environment file with all required variables
# -----------------------------------------------------------------------------
echo "Step 2: Creating environment file..."

cat > ${APP_DIR}/.env << EOF
# AWS Configuration - Auto-generated by ASG user data
# Generated at: $(date)
AWS_REGION=${AWS_REGION}

# S3 Buckets
S3_LANDING_BUCKET=${S3_LANDING_BUCKET}
S3_THUMBNAIL_BUCKET=${S3_THUMBNAIL_BUCKET}

# SQS Queue (main worker queue)
SQS_QUEUE_URL=
SQS_VISIBILITY_TIMEOUT=300
SQS_MAX_MESSAGES=10

# Preview Queue (this worker's queue)
PREVIEW_QUEUE_URL=${PREVIEW_QUEUE_URL}

# OpenSearch
OPENSEARCH_ENDPOINT=${OPENSEARCH_ENDPOINT}
OPENSEARCH_INDEX_NAME=${OPENSEARCH_INDEX_NAME}
OPENSEARCH_USE_AWS_AUTH=true

# Worker Configuration
WORKER_THREADS=${WORKER_THREADS}

# Logging
LOG_LEVEL=INFO
LOG_FILE=${LOG_DIR}/worker.log

# Feature Flags
ENABLE_PREVIEW=true

# Preview Settings
PREVIEW_DPI=150
PREVIEW_MAX_PAGES=50
PREVIEW_QUALITY=85
EOF

# Set secure permissions on env file
chmod 640 ${APP_DIR}/.env
chown ${WORKER_USER}:${WORKER_USER} ${APP_DIR}/.env

# -----------------------------------------------------------------------------
# STEP 3: Create systemd environment file (for systemd to source)
# -----------------------------------------------------------------------------
echo "Step 3: Creating systemd environment file..."

# Create a systemd-compatible environment file (KEY=VALUE format, no export)
cat > /etc/cis-worker.env << EOF
# Systemd Environment File for CIS Preview Worker
# Auto-generated by ASG user data at $(date)

AWS_REGION=${AWS_REGION}
S3_LANDING_BUCKET=${S3_LANDING_BUCKET}
S3_THUMBNAIL_BUCKET=${S3_THUMBNAIL_BUCKET}
PREVIEW_QUEUE_URL=${PREVIEW_QUEUE_URL}
OPENSEARCH_ENDPOINT=${OPENSEARCH_ENDPOINT}
OPENSEARCH_INDEX_NAME=${OPENSEARCH_INDEX_NAME}
OPENSEARCH_USE_AWS_AUTH=true
WORKER_THREADS=${WORKER_THREADS}
LOG_LEVEL=INFO
LOG_FILE=${LOG_DIR}/worker.log
ENABLE_PREVIEW=true
PREVIEW_DPI=150
PREVIEW_MAX_PAGES=50
PREVIEW_QUALITY=85
EOF

chmod 644 /etc/cis-worker.env

# -----------------------------------------------------------------------------
# STEP 4: Create the preview worker systemd service
# -----------------------------------------------------------------------------
echo "Step 4: Creating systemd service..."

cat > /etc/systemd/system/cis-preview-worker.service << 'EOF'
[Unit]
Description=CIS Preview Worker - Auto Scaling Edition
After=network-online.target
Wants=network-online.target
Documentation=https://github.com/your-org/cis-file-search

[Service]
Type=simple
User=cis-worker
Group=cis-worker
WorkingDirectory=/opt/cis-file-processor

# Load environment variables from file
EnvironmentFile=/etc/cis-worker.env

# Set PATH to include virtual environment
Environment="PATH=/opt/cis-file-processor/venv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
Environment="PYTHONUNBUFFERED=1"

# Start the preview worker
ExecStart=/opt/cis-file-processor/venv/bin/python \
    /opt/cis-file-processor/src/preview_worker.py \
    --threads 2 \
    --idle-timeout 300

# Restart policy
Restart=on-failure
RestartSec=10s
StartLimitBurst=5
StartLimitIntervalSec=300s

# Graceful shutdown timeout (allow message processing to complete)
TimeoutStopSec=60s

# Resource Limits
LimitNOFILE=65536
LimitNPROC=4096
MemoryMax=2G
MemoryHigh=1.5G

# Security Hardening
NoNewPrivileges=true
PrivateTmp=true
PrivateDevices=true
ProtectSystem=strict
ProtectHome=true
ReadWritePaths=/var/log/cis-worker /tmp /opt/cis-file-processor/temp
ProtectKernelTunables=true
ProtectKernelModules=true
ProtectControlGroups=true

# Logging
StandardOutput=append:/var/log/cis-worker/preview-worker.log
StandardError=append:/var/log/cis-worker/preview-worker-error.log
SyslogIdentifier=cis-preview-worker

[Install]
WantedBy=multi-user.target
EOF

# -----------------------------------------------------------------------------
# STEP 5: Create startup script (alternative to direct Python execution)
# -----------------------------------------------------------------------------
echo "Step 5: Creating startup script..."

cat > ${APP_DIR}/start-preview-worker.sh << 'SCRIPT'
#!/bin/bash
# CIS Preview Worker Startup Script
set -e

APP_DIR="/opt/cis-file-processor"
LOG_DIR="/var/log/cis-worker"

# Source environment if not already loaded
if [ -f /etc/cis-worker.env ]; then
    set -a
    source /etc/cis-worker.env
    set +a
fi

# Log startup
echo "$(date): Starting preview worker..." >> ${LOG_DIR}/preview-worker.log

# Activate virtual environment and run worker
cd ${APP_DIR}
exec ${APP_DIR}/venv/bin/python ${APP_DIR}/src/preview_worker.py \
    --queue-url "${PREVIEW_QUEUE_URL}" \
    --threads "${WORKER_THREADS:-2}" \
    --idle-timeout "${IDLE_TIMEOUT:-300}"
SCRIPT

chmod +x ${APP_DIR}/start-preview-worker.sh
chown ${WORKER_USER}:${WORKER_USER} ${APP_DIR}/start-preview-worker.sh

# -----------------------------------------------------------------------------
# STEP 6: Validate configuration before starting service
# -----------------------------------------------------------------------------
echo "Step 6: Validating configuration..."

# Source environment for validation
set -a
source /etc/cis-worker.env
set +a

VALIDATION_FAILED=0

# Check required environment variables
if [ -z "${OPENSEARCH_ENDPOINT}" ]; then
    echo "ERROR: OPENSEARCH_ENDPOINT is not set!"
    VALIDATION_FAILED=1
fi

if [ -z "${PREVIEW_QUEUE_URL}" ]; then
    echo "ERROR: PREVIEW_QUEUE_URL is not set!"
    VALIDATION_FAILED=1
fi

if [ -z "${S3_LANDING_BUCKET}" ]; then
    echo "ERROR: S3_LANDING_BUCKET is not set!"
    VALIDATION_FAILED=1
fi

# Check if Python virtual environment exists
if [ ! -f "${APP_DIR}/venv/bin/python" ]; then
    echo "ERROR: Python virtual environment not found at ${APP_DIR}/venv"
    VALIDATION_FAILED=1
fi

# Check if preview_worker.py exists
if [ ! -f "${APP_DIR}/src/preview_worker.py" ]; then
    echo "ERROR: preview_worker.py not found at ${APP_DIR}/src/"
    VALIDATION_FAILED=1
fi

if [ ${VALIDATION_FAILED} -eq 1 ]; then
    echo "Configuration validation FAILED! Service will not start correctly."
    # Continue anyway to allow debugging
fi

# -----------------------------------------------------------------------------
# STEP 7: Test AWS connectivity
# -----------------------------------------------------------------------------
echo "Step 7: Testing AWS connectivity..."

# Test SQS access (get queue attributes)
if aws sqs get-queue-attributes \
    --queue-url "${PREVIEW_QUEUE_URL}" \
    --attribute-names ApproximateNumberOfMessages \
    --region ${AWS_REGION} > /dev/null 2>&1; then
    echo "SQS connectivity: OK"
else
    echo "WARNING: Cannot access SQS queue. Check IAM permissions."
fi

# Test S3 access
if aws s3 ls "s3://${S3_LANDING_BUCKET}/" --max-items 1 --region ${AWS_REGION} > /dev/null 2>&1; then
    echo "S3 connectivity: OK"
else
    echo "WARNING: Cannot access S3 bucket. Check IAM permissions."
fi

# -----------------------------------------------------------------------------
# STEP 8: Enable and start the service
# -----------------------------------------------------------------------------
echo "Step 8: Starting preview worker service..."

systemctl daemon-reload
systemctl enable cis-preview-worker.service
systemctl start cis-preview-worker.service

# Wait a moment and check status
sleep 5

if systemctl is-active --quiet cis-preview-worker.service; then
    echo "SUCCESS: Preview worker service is running!"
    systemctl status cis-preview-worker.service --no-pager
else
    echo "ERROR: Preview worker service failed to start!"
    echo "--- Service Status ---"
    systemctl status cis-preview-worker.service --no-pager || true
    echo "--- Journal Logs ---"
    journalctl -u cis-preview-worker.service -n 50 --no-pager || true
    echo "--- Error Log ---"
    tail -50 ${LOG_DIR}/preview-worker-error.log 2>/dev/null || true
fi

# -----------------------------------------------------------------------------
# STEP 9: Setup CloudWatch Agent for logging
# -----------------------------------------------------------------------------
echo "Step 9: Configuring CloudWatch Agent..."

if [ -f /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl ]; then
    cat > /opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json << 'CWCONFIG'
{
  "agent": {
    "metrics_collection_interval": 60,
    "run_as_user": "root"
  },
  "logs": {
    "logs_collected": {
      "files": {
        "collect_list": [
          {
            "file_path": "/var/log/cis-worker/preview-worker.log",
            "log_group_name": "/aws/ec2/cis-preview-worker",
            "log_stream_name": "{instance_id}/worker",
            "timezone": "UTC"
          },
          {
            "file_path": "/var/log/cis-worker/preview-worker-error.log",
            "log_group_name": "/aws/ec2/cis-preview-worker",
            "log_stream_name": "{instance_id}/error",
            "timezone": "UTC"
          },
          {
            "file_path": "/var/log/user-data.log",
            "log_group_name": "/aws/ec2/cis-preview-worker",
            "log_stream_name": "{instance_id}/user-data",
            "timezone": "UTC"
          }
        ]
      }
    }
  },
  "metrics": {
    "namespace": "CIS/PreviewWorker",
    "metrics_collected": {
      "cpu": {
        "measurement": ["cpu_usage_idle", "cpu_usage_iowait"],
        "metrics_collection_interval": 60,
        "totalcpu": true
      },
      "mem": {
        "measurement": ["mem_used_percent"],
        "metrics_collection_interval": 60
      }
    }
  }
}
CWCONFIG

    /opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl \
        -a fetch-config \
        -m ec2 \
        -s \
        -c file:/opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json
    echo "CloudWatch Agent configured"
else
    echo "CloudWatch Agent not installed, skipping..."
fi

echo "=========================================="
echo "CIS Preview Worker - Bootstrap Complete"
echo "Finished at: $(date)"
echo "=========================================="
